load("@j2cl//build_defs:rules.bzl", "j2cl_library")

package(
    default_visibility = ["//visibility:public"],
)

j2cl_library(
    name = "typesystemEngine-j2cl",
    srcs = glob(
        ["source/**/*.java", "source_gen/**/*.java"], exclude = [
            "**/BaseHelginsDescriptor.java",
            "**/IncrementalTypecheckingComponent.java",
            "**/InvalidationResult.java",
            "**/NonTypeSystemComponent.java",
            "**/SimpleTypecheckingComponent.java",
            "**/TypeSystemComponent.java",
            "**/BaseTypechecking.java",
            "**/IncrementalTypechecking.java",
            "**/CachingTypecheckingContext.java",
            "**/SimpleTypecheckingContext.java",
            "**/DoubleTermRules.java",
            "**/InequalityBlock.java",
            "**/Equations.java",
            "**/Inequalities.java",
            "**/NodeMaps.java",
            "**/State.java",
            "**/CoercionManager.java",
            "**/SubtypingUtil.java",
            "**/TypesUtil.java",
            "**/AbstractLanguageProcessor.java",
            "**/InequalitySystem.java",
            "**/RulesManager.java",
            "**/Type.java",
            "**/LegacyTypecheckingProvider.java",
            "**/ApplyRuleOperation.java",
            "**/AssignTypeOperation.java",
            "**/CheckSubTypeOperation.java",
            "**/ClearNodeTypeOperation.java",
            "**/ExpandTypeOperation.java",
            "**/ProcessReplacementRuleOperation.java",
            "**/SubstituteTypeOperation.java",
            "**/AddDependencyOperation.java",
            "**/RemoveDependencyOperation.java",
            "**/AbstractEquationOperation.java",
            "**/WhenConcreteBlock.java",
            "**/MultipleWhenConcreteBlock.java",
            "**/TargetBlock.java",
            "**/HUtil.java",
            "**/CacheNodeHandler.java",
            "**/MPSTypesystem.java",
            "**/SubtypingManager.java",
            "**/RuleSet.java",
            "**/DoubleRuleSet.java",
            "**/TypeSystemReporter.java",
        ]        
    ) + glob(
        ["j2cl_src/**/*.java"],
        allow_empty = True,
    ),
    deps = [
        "//core:kernel-j2cl",
        "//core/smodel:smodel-j2cl",
        "//core/patternRuntime:pattern-runtime-j2cl",
        "//core/components:components-j2cl",
        "//core/logging:logging-j2cl",
        "//core/openapi:mps-openapi-j2cl",
        "//core/util:util-j2cl",
        "//core/typechecking:typechecking-j2cl",
        "//core/mps-annotations:mps-annotations-j2cl",
        "//core/aspects/behavior/behavior-api:behavior-api-j2cl",
        "//core/aspects/behavior/behavior-runtime:behavior-runtime-j2cl",
        "//languages/baseLanguage/closures/runtime:closures-runtime-j2cl",
        "//languages/baseLanguage/collections/runtime:collections-runtime-j2cl",
        "@org_jetbrains_annotations-j2cl",
    ],
)
