load("@j2cl//build_defs:rules.bzl", "j2cl_library")

package(
    default_visibility = ["//visibility:public"],
)

j2cl_library(
    name = "editor-runtime-j2cl",
    srcs = glob(
        [
            "editor-runtime/source/**/*.java",
            "editor-runtime/source_gen/**/*.java",
            "actions-runtime/source/**/*.java",
        ],
        exclude = [
            "editor-runtime/source/jetbrains/mps/nodeEditor/memory/*.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/PlatformScrollingModelEmulation.java",

            "actions-runtime/source/jetbrains/mps/smodel/action/AbstractNodeSubstituteAction.java",
            "actions-runtime/source/jetbrains/mps/smodel/action/DefaultChildNodeSubstituteAction.java",
            "actions-runtime/source/jetbrains/mps/smodel/action/DefaultSimpleSubstituteAction.java",
            "actions-runtime/source/jetbrains/mps/smodel/action/ModelActions.java",
            "actions-runtime/source/jetbrains/mps/smodel/action/ReferentSubstituteActionsHelper.java",
            "actions-runtime/source/jetbrains/mps/smodel/action/SPropertySubstituteAction.java",

            # NOT supported for now Context Assistant

            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/ContextAssistantSettings.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/AbstractStepComboBoxButton.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/ContextAssistantButton.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/ContextAssistantButtonItem.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/ContextAssistantController.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/ContextAssistantPanel.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/ContextAssistantView.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/FocusUtil.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/MenuItemListStep.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/OverflowLayout.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/PanelCustomizations.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/StepComboBoxButton.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/SubListStep.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/TopLevelButtonCreatingVisitor.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/contextAssistant/WhatsThisActionItem.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_ContextAssistantComponent.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/assist/AncestorOrSmallCellContextAssistantFinder.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/assist/EditorContextAssistants.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/assist/EditorContextAssistantsController.java",

            # NOT supported for now Documentation

            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/MPSDocumentationEditorPane.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/MPSDocumentationHtmlUtil.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/MPSDocumentationManager.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/MPSDocumentationMarkup.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/MPSDocumentationScrollPane.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/MPSDocumentationToolWindowManager.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/MPSDocumentationUtil.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/PopupMouseListener.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/ui/MPSDocumentationPopupUI.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/ui/MPSDocumentationToolWindowUI.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/documentation/ui/MPSDocumentationUI.java",

            # DUPLICATED in j2cl_src - exclude source versions to avoid class conflicts

            "editor-runtime/source/jetbrains/mps/editor/EditorComponentTrackService.java",
            "editor-runtime/source/jetbrains/mps/ide/editor/MPSEditorDataKeys.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/AutoValidator.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/BracesHighlighter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/CellNavigator.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/CellTracker.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/CreateFromUsageUtil.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorAspectContributionsCache.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorComponent.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorComponentActions.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorComponentDecoration.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorComponentFocusTracker.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorComponentKeyboardHandler.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorComponentLayoutManager.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorComponentSettingsImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorContext.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorMessage.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorMessageIconRenderer.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorMessagesPanel.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorSettings.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorSettingsUISettingsListener.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EditorTooltipProvider.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/EmptyHighlighter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/FocusPolicyUtil.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/Highlighter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/HighlighterContribution.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/HighlighterMessage.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/HintPopupController.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/InspectorTool.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/IntentionActionsProvider.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/IntentionsSupport.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/LanguageRegistryHelper.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/MPSColors.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/MPSErrorDialog.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/Memento.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/MessagesGutter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/MyScrollBar.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/NodeEditorActions.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/NodeEditorComponent.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/NodeHighlightManager.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/NodeInformationDialog.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/PlatformEditorEmulation.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/ReferenceUnderliner.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/ReferencedNodeContext.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/SearchHistoryComponent.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/SearchPanel.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/SelectedLinePainter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/SubstituteActionComparator.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/assist/DefaultContextAssistantManager.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/assist/DelayedRunnable.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cellActions/CellAction_PasteNode.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cellMenu/CompletionHelper.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cellMenu/NodeItemCellRenderer.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cellMenu/NodeSubstituteChooser.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cellMenu/NodeSubstituteChooserHandler.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cellMenu/NodeSubstituteChooserUi.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cellMenu/NodeSubstitutePatternEditor.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/AbstractEditorRegistry.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/CellFinderUtil.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_Basic.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_Collection.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_Constant.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_Image.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_Label.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_Property.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorCell_URL.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/EditorFontMetricsImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/FontRegistry.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/PropertyAccessor.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/TextLine.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/cells/collections/AbstractContainer.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/commands/CommandContextImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/commands/CommandContextWithVF.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/configuration/EditorConfiguration.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/configuration/EditorConfigurationBuilder.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/deletionApprover/DeletionApproverImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/highlighter/EditorComponentCreateListener.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/highlighter/EditorHighlighter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/highlighter/HighlighterEditorList.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/highlighter/HighlighterEditorTracker.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/highlighter/HighlighterEventCollector.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/highlighter/HighlighterUpdateSession.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/hintsSettings/ConceptEditorHintSettingsComponent.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/inspector/InspectorEditorComponent.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/keymaps/AWTKeymapHandler.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/keymaps/KeymapHandler.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/leftHighlighter/BackgroundWithFoldingLinePainter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/leftHighlighter/FoldingButton.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/leftHighlighter/LeftEditorHighlighter.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/messageTargets/EditorMessageWithTarget.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/selection/SelectionManagerImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/selection/SelectionInfoImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/selection/NodeRangeSelection.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/sidetransform/EditorCell_STHint.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/ui/InputMethodRequestsImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/ui/InputMethodListenerImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/updater/UpdateSessionImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/updater/UpdaterImpl.java",
            "editor-runtime/source/jetbrains/mps/nodeEditor/updater/UpdaterRepositoryContentAdapter.java",
            "editor-runtime/source_gen/jetbrains/mps/editor/runtime/DocumentationProvider.java",
            "editor-runtime/source_gen/jetbrains/mps/editor/runtime/EditorUtil.java",
            "editor-runtime/source_gen/jetbrains/mps/editor/runtime/ErrorComponents.java",
            "editor-runtime/source_gen/jetbrains/mps/editor/runtime/HighlightUsagesSupport.java",
            "editor-runtime/source_gen/jetbrains/mps/editor/runtime/LanguageEditorChecker.java",
            "editor-runtime/source_gen/jetbrains/mps/editor/runtime/impl/cellMenu/EnumSPropertySubstituteInfo.java",
            "editor-runtime/source_gen/jetbrains/mps/editor/runtime/impl/cellMenu/EnumSPropertyTransformationItemFactory.java",

            "editor-runtime/source/jetbrains/mps/lang/editor/cellProviders/ReferenceCellContext.java",
        ],
    ) + glob(
        [ "editor-runtime/j2cl_src/**/*.java"],
        exclude = [
            "editor-runtime/j2cl_src/jetbrains/mps/nodeEditor/assist/DefaultContextAssistantManager.java",
            "editor-runtime/j2cl_src/jetbrains/mps/nodeEditor/ui/InputMethodRequestsImpl.java",
        ],
        allow_empty = True,
    ) + glob(
         [ "actions-runtime/j2cl_src/**/*.java"],
    ) + glob(
        ["web-runtime/**/*.java"],
        allow_empty = True,
    ),
    deps = [
        "//editor/editor-api:editor-api-j2cl",
        "//core/typesystemEngine:typesystemEngine-j2cl",
        "//core/typechecking:typechecking-j2cl",
        "//editor/editorlang-runtime:editorlang-runtime-j2cl",
        "//core/aspects/behavior/behavior-api:behavior-api-j2cl",
        "//core/aspects/behavior/behavior-runtime:behavior-runtime-j2cl",
        "//core/smodel:smodel-j2cl",
        "//core:kernel-j2cl",
        "//core/openapi:mps-openapi-j2cl",
        "//core/mps-annotations:mps-annotations-j2cl",
        "//core/components:components-j2cl",
        "//core/mps-messaging:mps-messaging-j2cl",
        "//core/vfs:vfs-j2cl",
        "@org_jetbrains_annotations-j2cl",
        "//languages/baseLanguage/closures/runtime:closures-runtime-j2cl",
        "//languages/baseLanguage/collections/runtime:collections-runtime-j2cl",
        "//languages/baseLanguage/tuples/runtime:tuples-runtime-j2cl",
        "//core/aspects/feedback/messages-for-legacy-constraints:messages-for-legacy-constraints-j2cl",
        "//core/logging:logging-j2cl",
        "//core/util:util-j2cl",
        "@elemental2//:elemental2-dom-j2cl",
        "@elemental2//:elemental2-core-j2cl",
    ],
)
