package jetbrains.mps.project.io;

/*Generated by MPS */

import jetbrains.mps.annotations.GeneratedClass;
import jetbrains.mps.components.CoreComponent;
import jetbrains.mps.project.structure.modules.ModuleDescriptor;
import jetbrains.mps.vfs.IFile;
import jetbrains.mps.project.MPSExtentions;

/**
 * Now it's CoreComponent, although without any relevant code to justify single instance / component status.
 * Perhaps, if we add configuration mechanism to plug other module persistence, CC would make more sense.
 */
@GeneratedClass(nodeId = "557142600900286111", model = "r:c7bbaee3-030a-4940-995f-2174babaf670(jetbrains.mps.project.io)")
public class DescriptorIOFacade implements CoreComponent {

  public DescriptorIOFacade() {
  }
  public DescriptorIO<? extends ModuleDescriptor> fromFileType(IFile file) {
    return null;
  }

  private static DescriptorIO<? extends ModuleDescriptor> fromExtension(DescriptorIOProvider standardProvider, String path) {
    return null;
  }

  /**
   * 
   * @deprecated It's {@code CoreComponent} , obtain proper instance though platform
   */
  @Deprecated
  public static DescriptorIOFacade getInstance() {
    // 1 use in mbeddr
    return new DescriptorIOFacade();
  }

  public boolean isModuleDescriptorFile(IFile file) {
    return false;
  }
}
